# Generated by Django 4.2 on 2024-05-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_cursos', '0002_alter_estudiante_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='registro_cursos.estudiante'),
        ),
    ]
